# lint_and_test.yml
name: Lint and Test

on:
  push:
    branches-ignore:
      - "prod*"
    tags-ignore:
      - "*"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run flake8 linter
        run: |

          flake8 ddb_single --max-line-length=120
          flake8 tests --max-line-length=120
          flake8 setup.py --max-line-length=120

      - name: Run unittest
        run: |
          docker compose up dynamodb-local -d
          coverage run -m unittest discover -s tests/
          coverage report
