# lint_and_test.yml
name: Lint and Test

on:
  push:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    services:
      dynamodb:
        image: amazon/dynamodb-local:2.0.0
        ports:
          - 8000:8000
        options: --name dynamodb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run flake8 linter
        run: |
          poetry run flake8 .

      - name: Run unittest
        run: |
          poetry run pytest --cov=ddb_single -v

      - name: Test Build
        run: |
          poetry build

      - name: Test Generate docs
        run: |
          cp ./readme.md ./docs_src/readme.md
          poetry run sphinx-apidoc -f -o ./docs_src ./ddb_single
          poetry run sphinx-build ./docs_src ./docs
